---
title: "R Cookbook for Agricultural Research"
author: "李誠紘 Cheng Hong, Li"
date: "`r Sys.Date()`"
knit: "bookdown::render_book"
bibliography: [book.bib, packages.bib]
biblio-style: apalike
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
github-repo: MullerLi/rcookbook-agri
description: "利用R程式語言完成農學試驗的統計分析"
url: 'https://mullerli.github.io/rcookbook-agri/'
---

# 關於

這是一本關於統計程式語言 R 的筆記，嘗試 (用白話文) 記錄我在 **農業試驗研究** 上使用的 R 程式語言。

## 這是什麼?

這是一個利用 [R](https://zh.wikipedia.org/wiki/R%E8%AF%AD%E8%A8%80) bookdown 撰寫，部屬在Github Page上的電子書。

這是我的學習筆記、速查本。

這本書包含農業研究常用的統計學、試驗設計學、資料繪圖的 R 程式語言。

要讀懂這本書，基礎的試驗設計學知識是必須的。

本書使用到的套件，複製到R環境執行即完成安裝與啟用：
```{r include=TRUE}
pkgs <- c('car','MASS','magrittr','tidyverse','lme4','lmerTest','multcomp','agricolae','dplyr','lsmeans','emmeans','psych')
if (!any(pkgs %in% installed.packages())) {install.packages(pkgs[!pkgs %in% installed.packages()])}
invisible(lapply(pkgs , library , character.only=TRUE))
```


本書的R版本
```{r}
sessionInfo()
```

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
library(formatR)
library(knitr)

```
